//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Автомобиль выдаётся заказчику после оплаты стоимости ремонта, оплата производится в бухгалтерии СТО. После окончания ремонта автомобиль должен быть вывезен с территории ремонта в течении 3-х дней. При простое автомобиля на СТО более 3-х дней ввиду отсутствия платы, на время ожидания запчастей или по другим причинам, не зависящим от СТО, с заказчика взимается плата на использование территории из расчёта один день: в цехе 600 р., во дворе - 140 р. Выдача автомобилей производится с 9 до 12 и 13 до 17 часов.")]
        public string AgreementConditions {
            get {
                return ((string)(this["AgreementConditions"]));
            }
            set {
                this["AgreementConditions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("При покупке исполнителем для автомобиля заказчика запчастей и материалов у третьи" +
            "х лиц делается наценка 20% на их стоимость.")]
        public string TermsPurchaseMaterials {
            get {
                return ((string)(this["TermsPurchaseMaterials"]));
            }
            set {
                this["TermsPurchaseMaterials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("слесарные – 2000км пробега или 2 месяца, рихтовано-покрасочные – 4 месяца. Гарант" +
            "ийные обязательства на работы выполняются фирмой только при предъявлении акта пр" +
            "иемки автомобиля и техпаспорта(доверенности).")]
        public string Guarantee {
            get {
                return ((string)(this["Guarantee"]));
            }
            set {
                this["Guarantee"] = value;
            }
        }
    }
}
