//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStation.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbSSContext : DbContext
    {
        public DbSSContext()
            : base("name=DbSSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationModel> Application { get; set; }
        public virtual DbSet<CarModel> Car { get; set; }
        public virtual DbSet<ContactPersonModel> ContactPerson { get; set; }
        public virtual DbSet<ContractorModel> Contractor { get; set; }
        public virtual DbSet<EmployeeModel> Employee { get; set; }
        public virtual DbSet<MarkModel> Mark { get; set; }
        public virtual DbSet<MaterialModel> Material { get; set; }
        public virtual DbSet<ModelModel> Model { get; set; }
        public virtual DbSet<NomenclatureModel> Nomenclature { get; set; }
        public virtual DbSet<OptionModel> Option { get; set; }
        public virtual DbSet<OptionCustomerModel> OptionCustomer { get; set; }
        public virtual DbSet<PostModel> Post { get; set; }
        public virtual DbSet<PowerOfAttorneyModel> PowerOfAttorney { get; set; }
        public virtual DbSet<ReasonModel> Reason { get; set; }
        public virtual DbSet<ReasonCustomerModel> ReasonCustomer { get; set; }
        public virtual DbSet<TypeManifestationModel> TypeManifestation { get; set; }
        public virtual DbSet<TypeNomenclatureModel> TypeNomenclature { get; set; }
        public virtual DbSet<TypeRepairModel> TypeRepair { get; set; }
        public virtual DbSet<UnitModel> Unit { get; set; }
        public virtual DbSet<UserModel> User { get; set; }
        public virtual DbSet<ViewСontractorModel> ViewСontractor { get; set; }
        public virtual DbSet<WorkModel> Work { get; set; }
        public virtual DbSet<WorkingHourModel> WorkingHour { get; set; }
    }
}
