//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomenclatureModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NomenclatureModel()
        {
            this.Material = new HashSet<MaterialModel>();
            this.Work = new HashSet<WorkModel>();
        }
    
        public int Number { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Type { get; set; }
        public decimal Price { get; set; }
        public int Code_unit { get; set; }
        public string VendorCode { get; set; }
        public string Descriprion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialModel> Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkModel> Work { get; set; }
        public virtual TypeNomenclatureModel TypeNomenclature { get; set; }
        public virtual UnitModel Unit { get; set; }
    }
}
