//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionCustomerModel
    {
        public System.Guid ID { get; set; }
        public int Number { get; set; }
        public System.Guid ID_option { get; set; }
    
        public virtual ApplicationModel Application { get; set; }
        public virtual OptionModel Option { get; set; }
    }
}
