//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserModel
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public bool Administrator { get; set; }
        public System.Guid ID_employee { get; set; }
    
        public virtual EmployeeModel Employee { get; set; }
    }
}
