//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkModel
    {
        public System.Guid ID { get; set; }
        public int Number_nomenclature { get; set; }
        public System.Guid ID_workingHour { get; set; }
        public int Amount { get; set; }
        public decimal NormOfTime { get; set; }
        public System.Guid ID_reasonCustomer { get; set; }
    
        public virtual NomenclatureModel Nomenclature { get; set; }
        public virtual ReasonCustomerModel ReasonCustomer { get; set; }
        public virtual WorkingHourModel WorkingHour { get; set; }
    }
}
